### ISSUE TITLE
Apply to Creative Scotland

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#100]
We have recently applied to Arts Council England.  

Scotland has a similar Arts Council with a similar remit, so it would be interesting to apply to them as well, because our project could be hosted in Glasgow. 

https://www.creativescotland.com/funding/funding-programmes/open-fund-sustaining-creative-development

# Resources 
https://www.dropbox.com/home/eQuality%20Time/Staff%26TrusteesOnly/FundingAndOtherApplications/Applying/Scottish%20Arts%20Council. 

# TODO 
- [x] Get trustee permission 
- [x] Go through all the documents live 
- [ ] Rewrite the Ferros Documents 
       - [ ] Seperate in the individual paragraph levels 
- [ ] Create the supporting docs 
       - [ ] Risk assesment
- [ ] Submit

**Comment by joereddington** [comment]
Okay, I have a range of good feedback from Roy about how to structure this, and I should look into doing a full rewrite on that basis.  No, I have emails to write to Bambo, and to Kate.

**Comment by joereddington** [comment]
This is dependant on another project, the Ferros one. #94

**Comment by joereddington** [comment]
#94 is now done so this is live...

## 01/10/21 09:42 to 10:34, Grant for Arts Council Scotland  +EQT
* I created the application Folder in Dropbox and have put the application form in it. 
* I have read [the guidance](https://www.creativescotland.com/__data/assets/pdf_file/0018/83223/CS-Open-Fund-for-Organisations-Oct.pdf) and the FAQ 

* Some notes, mostly for when it diveges from ACE 
  * 14th October is the Christmas deadline 
  * "We do not support feasibility studies"
  * "We will be placing a strong emphasis on risk assessment and have 
provided a template to help you with this element of your application. 
You must submit this completed template with your application. " 
  * " If there are any items in your Project Income table which are covered 
    as being in-kind (such as volunteer staffing, discounted space 
    bookings etc) you need to ensure that they are also given a value 
    and included in your income table. Here is an example Project 
    Income table showing some of the key things to consider when filling 
    out this table: " 

* I asked the CEO's if there are any potential issues I should be aware of. 

* Attempted to fill it out, but some combination of firefox and dropbox and word aren't playing well. I'm going to relaunch Firefox and try againrefox  
* Grumble. 
* 
## 06/10/21 14:33 to 14:59, Now it's time I did the scotland grant.  +EQT
* It's not as close as I would like to ACE 
* Yeah, it's a reasonably significant rewrite 
* I've put some text in
* The audience development plan isn't a goer. 
* I should find out what an activity pal nis 

Next action - is to copy the ferros document and 'cut and paste' all the content into this file.

**Comment by joereddington** [comment]
## 11/10/21 13:55 to 15:50, Okay Arts grant  +EQT
* Cut everything out of the old document 
* Cut a bunch of STUFF out of the Audience development plan as well. 
* It looks like I'll need to do a lot of rewriting. 
* Started the rewriting, actually doing okay on the first couple. The word limits are generous and we're working with it. 
* First two done - and actually feel like there are ways that it's an improvement on the other grant (goals at the front, stages made explicit, that sort of THING)  
* The third... is done but needs a bit of expanding. 
* I'm a bit... done? A bit fed up. But I've made serious progress. I like the idea that I could crack it properly today.

**Comment by joereddington** [comment]
Did a bunch of work on this yesterday and today - including creating a FAQ webpage, which was a fun experiment.  It's currently with YS.

**Comment by joereddington** [comment]
Submitted.
