### ISSUE TITLE
Set up Free adwords from Google 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#103]
eQuality Time is elegible for a Google Ad Grant, and that might be useful for WWW or OVF (or indeed, many other projects). 

One of our trustees has found a volenteer who would be willing to run it for us, which is nice. 

We have a [nonprofits at google account]( https://www.google.com/nonprofits/ ) which has two administrators (JR's personal account and as of today, JR's work account).  

There are a number of hoops to jump through:
 
- [x] [Set up Google Analytics](https://github.com/eQualityTime/Public/issues/103#issuecomment-593937720)
         - [ ] Tracking code on WWW site 
         - [x] Tracking code on EQT site 
         - [x] Tracking code on CommuniKate site 
         - [ ] Tracking code on OVF site  
         - [ ] Tracking code on Flowers For Turing
- [x] [Set up a Google Ads account ](https://github.com/eQualityTime/Public/issues/103#issuecomment-593937720)
- [x] [Apply for the ad grant](https://github.com/eQualityTime/Public/issues/103#issuecomment-593937720)
- [ ] Check everything is working (and that we can use the grant for sub-projects) 
- [ ] Thoroughly brief volenteer. 
        - [ ] Brainstorm the sort of words we want to see, the area we want to see them in. 

# Future Projects
* Make the GA tracking code also include file downloads - we want to know the sucess of our downloads. 
   * This looks interesting on the topic: https://ga-dev-tools.appspot.com/campaign-url-builder/

**Comment by joereddington** [comment]
I've been working on this today, and livestreaming it [here](https://youtu.be/C2_Fq00sJoA) 

I seperately set up a Google Analytics Account using my joeequalitytime@gmail.com account and added tracking code for equalitytime.co.uk and CommuniKate. 
* Equality Time UA-159578060-1 
* CommuniKate UA-159578060-2 
* White Water Writers UA-159578060-3
* The Open Voice Factory UA-159578060-4 



I used my joe.reddington@gmail.com account to work though [this list](https://www.google.com/nonprofits/account/org/AOPUvx43wafCupkVAqGv6nP4erKW609hOrSd2fzrnMlZFiqvVsE0CLzbqDmBhqDA636o_H-1LUZ0htrS1dRRyJ8LynqJuvMVvGzs-8fVOxpUpfPnel1s5_4/enrollments/grants), which included (re?) creating a Google Ads account with the number 568-132-4682 (this is the second such account in a few minutes, the first one was rejected because the currency needs to be USD - I'm unsure about how we ended up with a different number.

There where some elements of concern: 

> The Ad Grants program requires a high-quality website that has a robust and clear description of your organization and mission with substantial content, updated events and information, clear navigation, and clear calls to action. Your site’s content must be unique to your organization. Your website must function well, load quickly, not contain broken links, and be secure with HTTPS. See the full website policy at https://support.google.com/grants/answer/1657899. 

...I'm a little worried that we'll have to go though this for every seperate project website. 

However, the process so far has been relatively simple - I've filled out the pre-qualification survay (which felt a lot more like data gathering than evaluation): 

![Screenshot 2020-03-03 at 13 04 51](https://user-images.githubusercontent.com/4369547/75778400-a0374e00-5d4f-11ea-982e-5e4b828fc3ab.png)

We now have to wait for approval: 
![Screenshot 2020-03-03 at 13 10 54](https://user-images.githubusercontent.com/4369547/75779251-3455e500-5d51-11ea-899e-26e064b9cc11.png)

**Comment by joereddington** [comment]
![Screenshot 2020-03-05 at 10 39 46](https://user-images.githubusercontent.com/4369547/75973921-e0bcd600-5ecd-11ea-913d-cc5aacd44215.png)

**Comment by joereddington** [comment]
Let's have another look at this. Streaming on https://youtu.be/Piu6bHtoqhE - probably from about 1 hour ten minutes
![Screenshot 2020-03-23 at 08 17 04](https://user-images.githubusercontent.com/4369547/77295969-b9904200-6cde-11ea-95bb-9dd83aaab39e.png)
(This is definately ambigious) 

Okay, went though the process again: 

![Screenshot 2020-03-23 at 08 21 47](https://user-images.githubusercontent.com/4369547/77296333-61a60b00-6cdf-11ea-8550-811899c0e8ea.png)

**Comment by joereddington** [comment]
![Screenshot 2020-03-26 at 08 25 30](https://user-images.githubusercontent.com/4369547/77625485-94e4d600-6f3b-11ea-8a58-6ca66abd39a6.png)

**Comment by joereddington** [comment]
I filled it out today again. If it doesn't work then I'll have to do some work on the site.

**Comment by joereddington** [comment]
Today I: 

* Rewrote the 'about us' page on EQT and made it the main page 
* Filled out the form and submitted it again. 

![Screenshot 2020-11-16 at 09 53 13](https://user-images.githubusercontent.com/4369547/99238473-abed7680-27f1-11eb-833b-18becc04451f.png)

**Comment by joereddington** [comment]
It's been blogged a few times. Long done. :)
