### ISSUE TITLE
Have a balanced system for marketing

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#107]
This includes 

* Email newsletter 
  * including open and enguagement metric
* social media calendar 
  * including some notice for each of the personas we developed here: https://github.com/eQualityTime/Public/issues/21 
* use of google ad words grant 

# Todo 
 - [ ] Read up properly on the GDPR rules 
 - [ ] Release new WWW website 
 - [ ] Create a google sheet for the social media calendar

**Comment by joereddington** [comment]
Okay, two tasks are currently in the list, only the social media calendar is different. 

I've set up the Social Media calendar. in the G-Suite.

**Comment by joereddington** [comment]
The WWW contact list is happening in another project https://github.com/eQualityTime/Home/issues/108 - but I should send out press contacts as well. 

Google Ads really needs more time and space.
