### ISSUE TITLE
Prepare for Furlough

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#112]
At their meeting on 1st April,  eQuality Time’s trustees decided to put the COO (the only current member of staff) into furlough from the 6th April.

The decision process and reasoning are covered in this briefing document that was written ahead of the meeting: [eQuality Time Coronovirus Response](http://equalitytime.co.uk/wp-content/uploads/2020/04/eQuality-Time-Coronovirus-Response.docx).

Until 6th of April, the COO will be spending his time making sure that any project partners or volenteers  have everything they need to keep the organisation working during the furlough.

# TODO 
- [x] Write briefing document for trustees and send for feedback 
- [x] Rewrite based on feedback. 
- [x] Tell TJR her jobs for the furlough
- [x] Email the LaTeX volenteer about setup 
- [x] Add email information to the briefing document 
- [x] Set up out-of-office 
- [ ] Ping about reviewing the last payments 
- [x] Email the document out. 
- [x] Messaged cover artist

**Comment by joereddington** [comment]
I have come back from (the first) furlough.  The absense went well, although there were some improvements to make: 

* I should have set joe@ to forward everything to admin@ 
* I should have included eleanor in the 'if you know this person' 
* Someone should have been given the accounts job 
* Should have considered it might be for a much longer period.

**Comment by joereddington** [comment]
I should blog this, I put a redacted version on facebook...
