### ISSUE TITLE
Hastag Poundsign

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#120]
With partners at Glasgow University and Northumbria University, we’ve been awarded £40,000 in funding from Not-Equal for a new project.

The project has the working title “Hastag Poundsign” until we can come up with something better.

You can find out more about it [here](https://equalitytime.co.uk/6493/2021/02/11/new-fake-news-project/)

Our role is that co-ordination of the domain experts, with a view to working out how to deliver this as a long term intervention.  Also checking in with the funder. 

# TODO
- [x] Review and upgrade child protection
- [x]  Share upgraded child protection policy. 
- [x]  Put together list of people who might be able to help
- [x]  Check DBS numbers
- [x]  Sign document and return to the universities 
- [x]  Ask Gemma if she'd like to write up some reflections on the blog 
- [x] Get content on website 
- [x] Set up the Dreamhost URL so we can set up Google Ads 
- [x] Get the Analytics set up for the page 
- [x] Set up Google Ads 
- [x] Redo the website with bells and whistles. 
- [x] Get report written 
- [x] Brainstorm future projects
- [x] Setup new project for the EQT follow on.

**Comment by joereddington** [comment]
Okay. Site is set up. The domain name is done. The github redirect is done.  Next THING is Google ads. I've done the link from the Google Analytics account. 
- [x] Confirm that projectreal.co.uk is a subdomain.

**Comment by joereddington** [comment]
![Screenshot 2021-08-25 at 10 45 38](https://user-images.githubusercontent.com/4369547/130768534-e4e6c33b-5d13-4d04-b45d-b73a28ad668f.png)
