### ISSUE TITLE
New Flowers For Turing Website

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#122]
# Background
Okay, so the currently flowers for turing website looks a little old and bland: 
![Screenshot 2021-03-17 at 08 19 29](https://user-images.githubusercontent.com/4369547/111436182-96ce1900-86f9-11eb-9024-d0d84e763f4f.png)

More to the point, it's also got a selection of typos and bugs, it's hosted on dreamhost, which have fallen out of favour with us, and it's very much not set up for any sort of analytics or use of our new Google Grant. 

So, I want a new site that is: 

* Hosted on github pages (because _I_ like it, and because we have a reasonably large number of technical donors who would also appreciate it
* Attractively written 
* Has a proper, clear, donation funnel, and the ability to know where our donors come from (email, reddit, facebook) 
* Has solid paypal intergration so we can take large donations. 

# Resources
* The current site is: http://www.flowersforturing.equalitytime.co.uk/ 
* The current github pages version is https://equalitytime.github.io/FlowersForTuring/ 
* The repo is https://github.com/eQualityTime/FlowersForTuring

# TODO 
- [x] Move the remaining content over to the github pages site
- [x] Draw out the funnel you want people to take. 
- [x] Edit the images - they are currently links to a website that will go offline. 
- [x] Fix footer
- [x] Test in Chrome
- [x] Add images to FAQ
- [x] sort out image css 
- [x] Look at the analytics for the old site to see what we have in terms of mobile/desktop and so on.](https://github.com/eQualityTime/Public/issues/122#issuecomment-813849328)
- [x] Ask for feedback on design
- [x] Add GA and set up funnel. 
- [ ] Delete old site
- [ ]  delete old website
- [ ] Write for the United states
- [ ] Confirm that donating works.
- [x] Add the new pages  (come from reddit, come from facebook, come from google ads, thank you for doing the thing, can you please share our STUFF) 
- [ ] Get a resolution to https://webmasters.stackexchange.com/questions/133860/embedding-a-paypal-form-in-the-website?fbclid=IwAR2TXdHzF6MQQK0oTLfximqPZQ-SVhkzz3f3ZYxhYoGmSGkAOtMDn23Y4T4 
- [x] Create Google Ads Campaign
- [ ] Check paypal donation on Mobile.

**Comment by joereddington** [comment]
So it actually looks like testing paypal should be higher on the list incase I need to host somewhere else.

**Comment by joereddington** [comment]
Some data: 

![Screenshot 2021-04-06 at 07 05 33](https://user-images.githubusercontent.com/4369547/113666098-972d5480-96a6-11eb-9f9f-bf8b323f544c.png)
![Screenshot 2021-04-06 at 07 03 51](https://user-images.githubusercontent.com/4369547/113666100-985e8180-96a6-11eb-8dc4-8c913513c3ac.png)
![Screenshot 2021-04-06 at 07 03 37](https://user-images.githubusercontent.com/4369547/113666105-98f71800-96a6-11eb-82f4-0e599579dfab.png)

**Comment by joereddington** [comment]
Hivemind! I need you to look at the new Flowers For Turing Website and tell me what you think about it.  Some of you care about typos, some alt text, some images, and some css. I want it all.  

I'm really excited about this year (I didn't run it last year because of the combination of the Pandemic and Leo's birth) - so excited that I'm belatedly properly embracing *actual* approaches like 'funnels' and 'a/b testing'.

**Comment by joereddington** [comment]
## 14/04/21 14:43 to 15:34, Working on Flowers for Turing Site +EQT
* Set up a please share page 
* Set up Google Analytics (easy on minima, there's a option in _config) did the same on the project real site
* Set up a funnel. (Tested later, first part works) 
* Fixed some typos and such  
* Created an ad campaign and asked for permissions

**Comment by joereddington** [comment]
Blog is at https://equalitytime.co.uk/6547/2021/05/12/new-flowers-for-turing-website/
