### ISSUE TITLE
Rewrite WWW site with a funnel.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#127]
I want the WWW site to have proper analytics so we can see how it works. Part of that is there being a clear journey and a funnel. 

The plan for the funnel is "Main page-> Teachers Page -> Contact Us" so I should write those pages. 

# TODO 
 - [x] Rewrite the issue
 - [x] Rewrite the header
 - [x] Make sure the links work from the front page 
 - [x] Draft a quick authors page 'you should contact your teachers', but in the meantime here's your FAQ
 - [x] Write the teachers page so it talks about a free book.  
	- [x] Put a set of photos in 
	- [x] Get a good set of quotes 
 - [x] Update the contact page so that it includes the free book.  
 - [x] merge ect. 

But... what is the minium example right now? 
* A working Author's page 
* A working teachers page 
* A Funnel in GA.

**Comment by joereddington** [comment]
## 12/05/21 15:40 to 16:07, Working on https://github.com/eQualityTime/Public/issues/127   +EQT 
It's moved forward. Its looks like a proper funnel. I need 

to complete that page (pictures and quotes) 
write the 'student' one. 
rewrite the homepage   
Update the funnel

**Comment by joereddington** [comment]
## 07/07/21 11:06 to 12:49, Rebuilding website. +EQT
* I've added a @media so the images work better on mobile
* I've made the links for teachers and students big and obvious and played with the css. 
* Added a quote and made the css work. 
* I've rewritten the student page, now needs images and quotes. 

## 07/07/21 13:10 to 14:47,  Working on https://github.com/eQualityTime/Public/issues/127 +EQT
* We resize images with "magick mogrify -resize 625 *.jpg "
* Used the resized images to fix theimage extension on Google Ads. 
* Fixed the student and teacher pages. Fixed other aspects. 
* Commited and pushed and is live. 

## 07/07/21 14:48 to 15:00, Google Analytics for site +EQT
* I've created a teacher path. 
* Looking at the analytics for the previous version of the site - 67% of the people who arrive at the home page drop off - and almost none of the rest end up anywhere interesting. 
* Wow - most of the people going through to the contact page came from the careers page. 
* Now back to the Google ads

**Comment by joereddington** [comment]
This is all done and live.
