### ISSUE TITLE
Produce accounts for 2021-2022

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#163]
# Todo
- [x] Find the Google Drive document to make notes in
- [x] Transfer accross the Open Voice Factory time
- [x] Create the spreadsheets and folders 
- [x]  Have the salies and NI and such as inovices to pay out. 

## Corrections
- [ ] Reimport the most recent numbers
- [ ] Add External examiner to Quickbooks 

# Resources 
* [The accounts folder](https://drive.google.com/drive/folders/1UOf5rUq8ogMqyaZFwnJWbk3pobxbMuhW)
* Last years accounts:

![Screenshot 2022-10-20 at 12 13 39](https://user-images.githubusercontent.com/4369547/196933977-f47f1cdf-1f9f-4f6b-b469-e81406c3662e.png)

**Comment by joereddington** [comment]
I looked at my timesheets and found I have spent 11.95 of my time on the Open Voice Factory since 4th November (which is the last point I looked at last time), Assuming you are fine with it, I will allocate 11.95% of my salary for the period to the ring-fenced OVF funds

**Comment by joereddington** [comment]
## 20/10/22 12:06 to 13:04, https://github.com/eQualityTime/Public/issues/163  +EQT
* Updating the project file 
* Creating a folder
* Worked out the right amount of money to transfer is £3,271.24 (the workings out are in the annual leave file) and have created a journal entry
* Checked and it now looks like our accounts are back, and we show a profit on the year (yay!) 
NA: on this is to create the files.
NA: Fill out the red shaded areas

**Comment by joereddington** [comment]
I've not been particularly good at making notes this year although I have been better about labeling the spreadsheets and so on.

**Comment by joereddington** [comment]
This is done and everything was filed a while back.
