### ISSUE TITLE
Supertitle resurection

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#169]
We've been asked to bring the Supertitle back online for a demonstration. 

This mostly involves finding the code, confirming it can work, and migrating it to the AWS servers. 

# Todos 
- [x] Find the repos 
- [ ] Check the repos work 
   - [x] Viewer 
   - [ ] Supertitle creator  
- [ ] Get an iplayer licence 
- [x] See if we can convert the code to python3 without trouble. 
- [x] Choose a program to demo  
- [ ] Create a subdomain (do we have to migrate the whole eqt site first? Kind of... we can run it on Dreamhost if we have to, but that feels lame...

**Comment by joereddington** [comment]
You may be familiar with a cartoon known as Danger Mouse.  Very much a part of my childhood.  There's an episode on iPlayer called Big Penfold - you can watch it here:  https://www.bbc.co.uk/iplayer/episode/b06jm3zq/danger-mouse-series-1-12-big-penfold?seriesId=b08s2brg

While watching it, you can also see the Spanish subtitles by going to https://whitewaterwriters.com/supertitle, selecting 'big penfold' and pressing play at the same time as you press play on the iPlayer (I like to lean my phone against the computer)

**Comment by joereddington** [comment]
I'm closing this on the basis the code does now work - it just needs funding.
