### ISSUE TITLE
Create Balanced set of accounts in Quickbooks

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#67]
Following #61, Quickbooks has all of our bank transactions imported into it.  

However, that doesn't mean that it gives us the information that we want, or that everything has been correctly filed.   Our grants are currently shown as income rather than liabilities and I (joe) am unsure about exactly how some aspects need to be set up.    

This issue will be completed when the Quickbooks accounts are producing useful reports, and they can be easily checked against the source documents.  We want the following useful reports: 

- [ ] The standard four accounting reports: income, balance sheet, equity, cash flow. 
- [x] A clear representation of our current core costs 
- [x] Expenditure against grant for each Grant, and the amount left in each catagory. 

The checking we want is: 
- [x]  That the Natwest and Unity transactions match up with statements at every point
- [ ]  That each folio in both the Expenditure 2.0 folder and the cash book also appears in Quickbooks.  (there is at least one missing) 

In addition we want 
- [ ] A blog post giving our current status at the end of the first quarter of our year (so extremely soon) 
- [ ] The trustees to have access and to be able to replicate any given report.  
 
# Plan
- [x] [Review the accounts that were produced by the accountant and compare them to what we think we can produce in Quickbooks.](https://github.com/equalitytime/public/issues/67#issuecomment-447628646)
- [x] [Check you can set end of year for quickbooks ](https://github.com/equalitytime/public/issues/67#issuecomment-447628646)
- [x] Experiment with modeling a grant as a libability account using the London Catalyst. 
- [x] Experiment with modeling a more complex grant as a libability using Awards for all (with Ring Fencing) 
- [x] Model the Comic Relief grant as a libability with sub accounts https://github.com/eQualityTime/Public/issues/67#issuecomment-448282642
- [x] Check how this affects the trial balance. https://github.com/eQualityTime/Public/issues/67#issuecomment-448282642
- [x] Work out how SHINE should have been done (it does have standard costs that are invoiced for) https://github.com/eQualityTime/Public/issues/67#issuecomment-448282642
- [x] Go throught *all* the transactions again in date order making sure  https://github.com/eQualityTime/Public/issues/67#issuecomment-448998242
   * the SHINE STUFF is billable  
   * Nesta and Comic Relief funds go through the right sub account. 
   * The stock asset items go into the right place.
- [x] Make sure that the COO salary is coming out of the right places. https://github.com/eQualityTime/Public/issues/67#issuecomment-448998242  
- [x] Reassign all 'stock asset' items from WWW (check what they properly should be first). https://github.com/eQualityTime/Public/issues/67#issuecomment-448998242
- [x] Work out how to mark a SHINE invoice as 'might get paid' 
- [x] Get list of camps to invoice from Keele  
- [ ] Correcting payment checks for PCC. 
- [ ] Review Rob's report to check in on where we are. 
- [ ] Add trustees to accoutns 
- [ ] Find out how to move 'invoices recived' through the system. 
- [ ] Fix author royalties. 
- [ ] Fix 19.40 for London Catalyst Fund.

**Comment by joereddington** [comment]
## 16/12/18 08:33 to 12:09, 
I've done the following: 

* I've reviewed the accounts originally reprepared for us, and checked a few assumptions: 
    * That the cash in the bank is accurate as of 31/8/2018
    * That the numbers in the elft most collum were from the previous years. 
* I have satisfied myself that the liabilities should have been much higher but might want to check that with a bright human. 
* I've also worked out that there are some expenses that I thought had been paid but unfortunately hadn't.   I've modified the plan to include that. 
* I've worked thought a bunch of the lectures in this Accounting 1 College course.  Currently on [Lecutre 8](https://www.youtube.com/watch?v=aIn7rnu1xTw), which got me to rewrite the issue around trial balances.

Most impontantly some aspects of accounting have clicked for me, and I believe that, having tried to do it with accounts, donors, classes, locations, and classes again, that the correct way to represent our grants is with accounts _but that those accounts are liability accounts_. I've rewritten the plan with that in mind.  

Next action as per plan.

**Comment by joereddington** [comment]
I've reached lecture 8: https://www.youtube.com/watch?v=aIn7rnu1xTw.  Currently checking if quickbooks does a trail balance.

**Comment by joereddington** [comment]
## 17/12/18 06:21,
I'm back. Our next action: 
  
* Experiment with modeling a grant as a libability account using the London Catalyst.

Now, I want to see how the trial balance changes as I do this.  

### 06:21 to 07:08,
Turns out balancing London Catalyst was a little harder because I'm missing £31...   I've fixed some bits at it's now short £0.56.  I'm happy with that.  (Baby is now awake anyway so this is a good time)

Now the test is... can I have this look good on a report? 

....I think so... I'm NOT there yet. But... 

- [  ] Get trustee to check folio 17.

**Comment by joereddington** [comment]
## 18/12/18 08:11 to 12:17, 
One of the points that I appeciated today was that the core funds are 'what's left' after I've sorted everything else out, so I need to sort everything else out.  The big bits to focus on today are: Keele and SHINE. 

## Keele
* I have imported all the invoices for keele 
* rewritten them according to the conversation we had with Yvonne in August. 
* Created a credit note to account for Yvonne's overpayment 
* Emailed my first invoice 
* Setup a task to do the next invoices. 
* Learned how to match invoices and deposits. 

## SHINE 
* I've been making the SHINE costs into billable expenses (this takes a long time) 
* I've then created one large invoice containing those expenses and then been deducting them. 
* I've reviewed the Document from kings and I'm conviced it's wrong. 

# Other 
* I've moved Nesta and Comic relief over to liability accounts. 
* I've done the same with Essex Challenge Prize and included a journal entry for corrections. 

## Left todo 
- [ ] Go throught *all* the transactions again in date order making sure the SHINE STUFF is billable and Nesta and Comic Relief funds go through the right subaccount. 
- [ ] Go through all the deposits and mark them off against the SHINE costs. 
- [ ] Go back and check that the SHINE costs have been invoiced properly 
 

### 13:50 to 14:24, Back again after lunch.   
Current State is that we are still 27 thousand in the red.  That's because the nesta and comic relief money is all a liabilty and I haven't connected up the amounts we have already paid.    There's also some correction to be made by putting the SHINE in order and making my salary payments come out of the right grants. 


## 18/12/18 15:44 to 16:30,
Reviewing and updating the document.

**Comment by joereddington** [comment]
## 19/12/18 14:46 to 17:07, +EQT
Did a push on working thought the natwest transactions. There are 209 to do. 
The first 50 were done by 15:44, the second 50 were done by 16:22, and I am on the 4th page (just: last one touched was on the 17/1/2018) so I'm getting slightly faster)

In the process: 
* I've been removing the school payments and recreating them as 'payments recived'
* I've been putting expenses in the correct catagory for Nesta and PCC 
* All camps before SHINE  15/8/2018 are considered simple sales (unless they were PCC) and I've been looking at the others on a case by case basis. 
* The correction I made to Londond Catalyst in folio 17 turns out to have been wrong and I've returned it to it's original state. There London Catalyst is still slightly out, but we will correct that later. 

# Todo
- [ ] Add a correcting payment for the PCC fund. (which should include 480 for administration costs)

**Comment by joereddington** [comment]
## 20/12/18 09:33 to 10:06 +EQT 

Another sprint today. I: 

* Completed going over the Natwest transactions
* Completed going over the Unity transactions 
	* Filled in some missing folio numbers/attachements

As a result we now know:
* The total amount we can charge to SHINE
* The total amount left to spend in Comic Relief and Nesta 
* The total amount of core funds that can be used to keep the organisation going. 


### 10:06 to 10:30, +EQT
Interupt for WWW


### 10:30 to 11:48, +EQT Back to project
Some other notes: 

* Comic Relief Offically started on the 1st August
* We have more to charge to SHINE than SHINE have to pay so some of that will come out of core costs. 
* Payments against invoice in UNity were deleted and recreated, I hope that doesn't cause a problem for the next import.
