### ISSUE TITLE
CR report

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#79]
# Summary 
The Comic Relief grant has ended and it's time to write the end-of-grant report.  Slightly hard because some of our accounts haven't gone through the system yet.   I've messaged our new (and highly responsive) CR contact to get the okay for sending through the *final* accounts a little later. (we don't get the final payment until we do) 

# Resources 
* [Pages were the reports live](https://www.comicrelief.com/funding/managing-your-funding/documents)
[Six month report](https://github.com/eQualityTime/Public/files/3134840/six.month.docx)
[Start up form]](https://github.com/eQualityTime/Public/files/3134850/eQuality.Time.docx)
[Guidance form](https://www.comicrelief.com/sites/default/files/downloads/8.%20Level%201%20grants%20-%20end%20of%20grant%20reporting%20guidance.pdf) 
https://www.comicrelief.com/funding/managing-your-funding/documents
  

# Plan 
- [x] Log into Gem, find out what you need to be doing. 
- [x] Draft answers - the real theme of this should be doing it properly (so: answering honestly and using the questions to really analyze what went wrong, rather than trying to spin the answers to make ourselves look good - I should be quite embarrassed by the answers if were doing it right.) https://www.comicrelief.com/funding/managing-your-funding/documents
- [x] Agggh! Read guidance!
   - [x] Add medical device recognition. 
   - [ ] "The information given in the report should make sense to a reader who is new to the project" - does that mean we should describe from scratch? Doesn't hurt but will need a bit of time later. 
   - [x] "Please complete the grant budget with the details that were agreed with Comic Relief at start-up for each year of your project in the grey columns" okay, but we changed our budgets halfway though... shouldn't we use the new ones?   https://github.com/eQualityTime/Public/issues/79#issuecomment-488625599
- [ ] Download and review conditions of grant. 
- [x] Copy and paste the targets from the startup sheet to keep consistent https://github.com/eQualityTime/Public/issues/79#issuecomment-488625599
- [x] Copy and paste the 'issues list' from the six month report to keep consistent (but check no new issues) https://github.com/eQualityTime/Public/issues/79#issuecomment-488625599 
- [x] Add in current budget estimations
- [ ] Put through simplewriter if we have time.

**Comment by joereddington** [comment]
[7. Level 1 grants - end of grant reporting form.docx](https://github.com/eQualityTime/Public/files/3134332/7.Level.1.grants.-.end.of.grant.reporting.form.docx)

**Comment by joereddington** [comment]
Last report 
[six month.docx](https://github.com/eQualityTime/Public/files/3134840/six.month.docx)

**Comment by joereddington** [comment]
Did the first few: 
[7.Level.1.grants.-.end.of.grant.reporting.form.docx](https://github.com/eQualityTime/Public/files/3134907/7.Level.1.grants.-.end.of.grant.reporting.form.docx)

**Comment by joereddington** [comment]
Drafted honest answers to most of the questions. 
[7.Level.1.grants.-.end.of.grant.reporting.form.docx](https://github.com/eQualityTime/Public/files/3136885/7.Level.1.grants.-.end.of.grant.reporting.form.docx)

**Comment by joereddington** [comment]
The files are on the other computer, so uploading this version now: 
[7.Level.1.grants.-.end.of.grant.reporting.form.docx](https://github.com/eQualityTime/Public/files/3137638/7.Level.1.grants.-.end.of.grant.reporting.form.docx)

**Comment by joereddington** [comment]
I've got all the information in. 
[7.Level.1.grants.-.end.of.grant.reporting.form.docx](https://github.com/eQualityTime/Public/files/3138012/7.Level.1.grants.-.end.of.grant.reporting.form.docx)

I got quite emotional writing this. It brought back some of the more stressful aspects of the project and so the wording might be a bit more honest than traditionally considered prudent.  I've tried to be clear about the failures (thoroughly outweighed by the successes) of the project but that sort of thing puts you in a combative mood for the rest of the questions.  I'm going to submit this to Gem, but might also rewrite tonight.
