### ISSUE TITLE
Slides for CM 2019

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#83]
I'm presenting at [Communication Matters](https://communicationmatters.org.uk/what-we-do/conference/) this year. It's on from 8th-10th September in Leeds. 

We have 40 minutes to present in, but we've got a lot of content and it would be great to leave a lot for Q&A.  We've got five main areas to hit, and we should prioritise those for usefulness (the fraud stuff is good and dramatic, but)

# Resources 
* [The timetable](https://eu.eventscloud.com/file_uploads/7cbb3245cfafb3689c1c84e1d026ff67_CM2019Timetablev7.pdf)
* [Previous talks given at CM](http://joereddington.com/researchpublications/) 

# People who should definately see the presentation before delivery: 
Kate, Clare, Simon 

# People who it would be good to get the take from: 
Brian, Trustees, Kat. 

# Todo: 
- [ ] Brainstorm the main concepts of the talk and check in Kate and so on.  
- [x] Think about how lightweight you'd like this to be - it would be great if all the slides were online in a non-powerpointy way, along with the talk itself. 
   -  [x] Try [these markdown generators](https://opensource.com/article/18/5/markdown-slide-generators) 
- [ ] Advertise the talk. 
   -  [ ] Social Media 
       - [ ] Twitter is a start 
       - [ ] You need to put it on facebook as well. 
   - [ ] In person 
   - [ ] By email - there's a bunch of AAC people to reconnect with there. 
- [ ] Get all the dates and the timelines together for the Comic Relief funding 
- [ ] Get contractor email and solicitors letter 
- [ ] Write out slides and reherseh 
- [x] Find out if you can stream the presentation. 
- [ ] Make sure all the tech works. 
- [ ] See if I know anyone in Leeds generally 
- [x] Check if the BJJ competition clashes... 
- [ ]  Check how long the presentation is. 

## The presentation itself. 
* What's the general idea: to talk about the Comic Relief Project   
   * Which bits of that will the audience find interesting? 
      * Medical Device (because some will be in the same buisness) 
         * Why it's a medical device 
        * That you have to pay for the documents 
        * what I ended up doing. (need disclaimer at the top of the page) 
      * Fraud (because everyone likes a horror story)
         * Do it direct from the summary you wrote 
         * Put the certificate online 
         * Checkovs gun - put this up front soon. 
      * Contacting important AAC people, who was great, who didn't reply. 
         * Big gratitude slide. 
      * How did we get the money? (Photos of process, and a link to the video) 
      * What we built! 

* Other bits that are needed: 
   * Introduction 

### Structure
* Title Slide
* Introduction - how you can follow along. (hey, you know what would be cool? Auto tweeting the slides on a timer...) 
   * where the slides are/transcript/live 
   * Interupting is very cool
   * Jazz hands? 
   * Ask for video for live
* What are we going to talk about (overall) and 'the bits of that we think are interesting to you' (fancy slide) 
* How we got given £45,000
   * Why we're talking about this?  
   * funder homepage 
   * 'old' device (maybe several) 
   * Video and short description 
   * Tech person in interview
   * Promised that medical device work would be done soon. 
   * shortlist meant it was 50-50.

**Comment by joereddington** [comment]
I wrote a blog here: http://equalitytime.co.uk/?p=6413&preview=true
