### ISSUE TITLE
Recruit casual artists for covers.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#86]
This project is to find and recruit artists to do covers for WWW books and give them all the information that they might need. 

# Background
White Water Writers is growing significantly and that is revealing some minor issues.  One of which is that our covers aren't particularly great, and they are getting harder and harder to produce (we're running out of stock photography). We've had some [really good covers some out of school volunteers](http://equalitytime.co.uk/6189/2018/02/18/cover-story/), but that's not reliable.  

Given we are a charity, we can't afford professional cover layout because that would just pass the costs directly to schools and other organisations. 

I was at [MCM Comic Con](https://www.mcmcomiccon.com/london/) in mid October, and many of the comic artists were offering sketches for £5-20.  These sketches weren't good enough to use as covers, but certainly they were close for our purposes and it certainly felt like £50-worth of sketching would give us something reasonable. The key here is that we aren't asking the artists to work more cheaply - we're just accepting a very cheap style.  We'd have to give fewer books to schools to make that work, but it might work out best. 

Ideally, of course, we'd work with a selection of different artists, so the covers didn't look too 'Samey'. 

There's three ways this could work, in, I assume, descending levels of artist-friendliness 
* I book in an artist in advance for a week "You are going to be given a brief on Monday and you must deliver by 3pm Friday"
* I send out the brief to interested parties "I need someone to do this brief by 3pm Friday, who fancies it?" 
* I let the kids pick from a shortlist "Some children need you to do this by 3pm Friday" 

# Plan
- [x] Worked my way around all of the artists with stalls at Comic Con. 
- [x]  Done a first-pass in person shortlisting, there were various reasons that some stalls were rejected: 
  * some artists didn't produce sketches that actually looked good, 
  * some artists were clearly too expensive 
  * some artists had a nice big crowd of people and I didn't have time, 
  * some basically only drew nude or erotic work or I just got a strange vibe. 
- [x]  [Go through the cards you picked up, check instagrams and do a second shortlist](https://github.com/eQualityTime/Public/issues/86#issuecomment-547350976)
- [x]  [Draft email for the group](https://github.com/eQualityTime/Public/issues/86#issuecomment-547350976)
- [x]  [Check in with Richard about reducing the number of copies of the book to pay for the covers](https://github.com/eQualityTime/Public/issues/86#issuecomment-547384814) 
- [x] [Send emails, with an effort to customise details](https://github.com/eQualityTime/Public/issues/86#issuecomment-547384814)
- [x] Trial three of the artists and itterate the process. Get feedback. 
- [ ] Add the introductory email as content in this issue 
- [ ] Open issue out publically for comment 
- [ ] Open issue out to recruit more artists to get to a stable cohort. 

# Resources for artists
* [Invoicing template if you haven't sent an invoice before](https://www.dropbox.com/s/8q8nu4y79xjfwt8/Here%27s%20an%20invoice%20you%20could%20send%20us%20-%20we%27ll%20understand%20it..docx?dl=0)  
* [Introduction Email](https://github.com/eQualityTime/Public/issues/86#issuecomment-547350976) 
* General details email
* [Amazon Cover template generator](https://kdp.amazon.com/en_US/cover-templates) - you aren't being paid for a full cover, you are being paid for an image someone else will put on it. But some artists like doing the whole cover anyway (for portfolios, or because they don't like how Joe 'fixes' their art 🤣). If you fancy putting it into a cover template, this is the one to use. 
* Examples of draft and final deliverables from one of the artists: 

![WhatsApp Image 2019-11-27 at 12 13 40](https://user-images.githubusercontent.com/4369547/69966727-e392de00-150e-11ea-8764-5e7a09306cec.jpeg)
![WhatsApp Image 2019-11-29 at 17 34 43](https://user-images.githubusercontent.com/4369547/69966734-e5f53800-150e-11ea-937a-0a9a90417740.jpeg)
![3BF2F218-0834-4B96-8794-0AB54AAEC381](https://user-images.githubusercontent.com/4369547/70526320-3e48bd00-1b41-11ea-9b2b-db781c5b307a.jpeg)
![BCA9AA31-748F-4BAB-90D5-9425C81D2486](https://user-images.githubusercontent.com/4369547/70526321-3ee15380-1b41-11ea-8cf5-05e30e191ec4.jpeg)

**Comment by joereddington** [comment]
Okay "Go through the cards you picked up, check instagrams and do a second shortlist."

"Draft email for the group" 

> Hello! I have your business card from Comic-Con!  I am interested in paying for very small but potentially regular commissions.  
> 
> I'm afraid I don't have good notes on how much I told each artist I spoke to, so I'm going to go though the whole thing here. 
> 
> I run a charity, one of our projects is "Going into Schools/Prisons and getting them to write books". We've done about 200 of them. 
> 
> Our covers are okay, but need some improvement.  At comic con there were a lot of people selling sketches for £5(!) to £20 and it was clear that, say, £50 worth of that standard of work would be a considerable improvement on our current set of covers. I should stress: I'm not looking to underpay anyone - I'm looking to pay you the right amount but for relatively little time so I have some sort of image to put in the middle of a cover.   
> 
> Here's how it works: our writers start on a Monday, and by the end of the Monday they know what characters they have, what they look like, and roughly what they'll be doing. They then write the book, finishing on Friday, and you'd have until 3pm Friday to deliver an image.  You'd be welcome to send over drafts and the like but we'd only use them to show the writers rather than provide meaningful feedback. At the moment I'm thinking £50 a time (because I can reduce the number of books we give the kids to free up that budget), and because I think that £50 worth of your art is worth having. 
> 
> We do about 80 of these a year at the moment, and I'm hoping to double that relatively soon so it's potentially regular work, although I'd ideally like to share it around a bunch of artists. 
> 
> * If you are interested, please email me back and say so, and I'd pick out a week that would be good, ideally I'd like to get this process running nice and smooth by Christmas.
> * If you'd like to know more about the project, you probably want [this site](http://whitewaterwriters.com/). You might also want [this post](http://equalitytime.co.uk/6189/2018/02/18/cover-story/), which is some complaining I did about schools providing their own covers
> * If you'd like to know more about this attempt to improve covers, including the Instagram's of the other eight or so artists I'm emailing, then you want to check out [this issue](xXXX). There is also a livestream of the work on it [available](http://joereddington.com/live)
> 
> Thank you. 
> 
> 
>

**Comment by joereddington** [comment]
> Richard! 
> 
> Can you have a quick read of [this](github link) and let me know if it makes sense to you? Particularly the 'we pay for this by giving the kids fewer books' part. If it works you'd have to send a couple of messages at the end of a Monday to the relevant artist, but less cover work...

**Comment by joereddington** [comment]
I got a 👍 from Richard and have emailed...about half of the shortlist in the end. 

J

**Comment by joereddington** [comment]
Trustees have pointed out that suppliers should be invoicing us, so I've written up a draft for anyone who hadn't done an invoice before here: https://www.dropbox.com/s/8q8nu4y79xjfwt8/Here%27s%20an%20invoice%20you%20could%20send%20us%20-%20we%27ll%20understand%20it..docx?dl=0

**Comment by joereddington** [comment]
Draft for blog/social

*Please DONT share this, because facebook will share the pic/link without comment, which is unhelpful, but equally please do tag anyone who might be interested* 

I'm looking for artists.    At MCM in October I saw various artists selling custom sketches for £20-£35 and thought "£50 worth of that sort of art would be good enought for us to use as a cover for WWW books". So I contacted a bunch and we've had some awesome covers come through that I'm really pleased with.   We've got several artists we're now working with but we'd like to have more because that gives us a variety of styles and some resilliance for when we're doing six or so books in a week.  So if you know anyone who does Good Art and would sell us a sketch for £50 of around this sort of quality please send them my way. 

I'm *hyper* aware that artists should be paid fairly, and I want to be very clear that I'm NOT looking for "Produce me a high quality professional cover for this low fee" I'm looking for "Give us a sketch that we can use in our cover for this book that these kids made for this set fee". It's very much "£50 worth of your art" rather than "Do lots of art for £50".  

What I need is: 

* Referals to artists/hobbists who you think might be interested 
* Any comments on the best way of phrasing this so it's clear that it's NOT an attempt to underpay for talent.

**Comment by joereddington** [comment]
The general details email looks like this: 

> Richard, X is the cover artist we'll be trialing next week, she's going to produce £50 worth of a cover image by 2pm next Friday (so you can show the writers before print). To be clear, she's producing a cover image, rather than a cover - so you still have full control of placement and title font and so on.  In the future we may progress to a 'you log in and the cover is already done' arrangement but that's where we are.  My understanding from talking to all the shortlisted cover artists is that it's far easier to to one headshot of a character for the front cover than two or more or a dynamic pose.  Please can you send her some short descriptions of major characters at the end of Monday.
> 
> X, Richard is our most experienced camp leader and is the person you'll work with the most. He's going to be on the ground with the writers from Monday to Friday and will press the final publication button.  My assumption is that he'll send you a selection of character ideas and then you are good to interpret them as you see fit.  One of the things we frequently ask writers is 'who would you case to play this character in the movie', and I suspect that would be useful to you, although it is obviously not expected that the illustration looks like the actor (otherwise you'd be drawing Emma Watson on a ridiculously regular basis).  He'd probably like in-progress photos, if only to show writers when they lose motivation.
> 
> Couple of general points we discovered in the last interation of this (I suspect this is how you already work):
> 
>     Analog/digital.  We prefer digital drawings to scanned in ones, and scanned and then digitally coloured is a nice middle ground.
>     If (and it very much isn't complusoury) you are going to do a background it's ideal if we get that as a seperate layer because it makes it a lot easier to fit the title in and so on.
>     Work-in-progress shots are very nice for social media, so feel free to throw them up on your channels, tag us (White Water Writers or me personally) and we'll boost. Also please let us know if you are okay with images you send us being used on social media.
>     Feedback is good, we like feedback - the more good feedback we get on the process the more that we can make it nice for everybody  :)
>     Invoice! You'll have to invoice us for the £50 because that's how the charity's payments work.  If you haven't done an invoice before - I put together a sample one at the bottom of this page. Feel free to send one in advance - I'll action it when Richard tells me he has a cover.  :)
> 
> I don't particularly need to be in the loop for futher conversation. You guys can take if from here.

**Comment by joereddington** [comment]
This should be closed and rewritten into an actual blog post for people to look at.

**Comment by joereddington** [comment]
(but check if you have already written the blog post)
