### ISSUE TITLE
Arrange AGM

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#91]
eQuality Time has an AGM coming up on the 15th December at the [Gestalt Centre](https://gestaltcentre.org.uk/) Postcode: NW1 0PT. 

Times: 

# Todo
- [ ] Confirm times/dates from email. 
- [ ] Put address 
- [ ] Get items printed 
- [ ] Send out pre-reading 
- [ ] 

# List of topics to discuss

**Comment by joereddington-public** [comment]
Things to talk about: 

* Progress on Robs recommendations 
* Formal approval of budget for the year 
* Vision document 
* Joe's hours 
* Choosing Accountants
